# Generated by Django 5.1.6 on 2025-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="item",
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(related_name="orders", to="payment.item"),
        ),
    ]
