# Generated by Django 5.1.6 on 2025-02-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_item_options_remove_order_item_order_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="item",
            new_name="items",
        ),
    ]
