# Generated by Django 5.1.6 on 2025-02-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_rename_item_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items_for_delete",
            field=models.JSONField(default=list, verbose_name="Временное хранилище"),
        ),
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("usd", "dollar"), ("rub", "ruble")],
                max_length=5,
                verbose_name="Валюта",
            ),
        ),
    ]
